name: Labeler
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: MaaAssistantArknights/issue-checker@v1.14
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          not-before: 2025-06-01T00:00:00Z
          include-title: 1
          sync-labels: 1
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler-localization.yml
          sync-labels: true
