name: Localization
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    if: github.repository == 'MIA-Development-Team/Made-In-Abyss'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      discussions: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm i --omit=dev
        working-directory: .github/scripts
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/localization.js')
            await script({github, context})